export const EDITOR_LANGUAGE_REGISTRY = [
  {
    id: 'html',
    aliases: ['HTML'],
    extensions: ['.html', '.htm', '.xhtml', '.vue'],
    supportLevel: 'native',
    family: 'markup',
    detail: 'Native Monaco HTML language service.',
  },
  {
    id: 'css',
    aliases: ['CSS'],
    extensions: ['.css'],
    supportLevel: 'native',
    family: 'stylesheet',
    detail: 'Native Monaco CSS language service.',
  },
  {
    id: 'scss',
    aliases: ['SCSS', 'Sass'],
    extensions: ['.scss', '.sass'],
    supportLevel: 'native',
    family: 'stylesheet',
    detail: 'Native Monaco SCSS language service.',
  },
  {
    id: 'javascript',
    aliases: ['JavaScript', 'JS', 'Node.js'],
    extensions: ['.js', '.mjs', '.cjs', '.jsx'],
    supportLevel: 'native',
    family: 'javascript',
    detail: 'Native Monaco JavaScript language service.',
  },
  {
    id: 'typescript',
    aliases: ['TypeScript', 'TS', 'TSX'],
    extensions: ['.ts', '.tsx'],
    supportLevel: 'native',
    family: 'typescript',
    detail: 'Native Monaco TypeScript language service.',
  },
  {
    id: 'json',
    aliases: ['JSON'],
    extensions: ['.json', '.jsonc'],
    supportLevel: 'native',
    family: 'data',
    detail: 'Native Monaco JSON language service.',
  },
  {
    id: 'markdown',
    aliases: ['Markdown', 'MD'],
    extensions: ['.md', '.mdx'],
    supportLevel: 'native',
    family: 'markup',
    detail: 'Native Monaco Markdown language service.',
  },
  {
    id: 'python',
    aliases: ['Python', 'Py'],
    extensions: ['.py', '.pyw'],
    supportLevel: 'lsp',
    family: 'python',
    serverLabel: 'Pyright',
    serverCommands: ['pyright-langserver'],
    serverArgs: ['--stdio'],
    rootPatterns: ['pyproject.toml', 'setup.py', 'requirements.txt', '.git'],
  },
  {
    id: 'c',
    aliases: ['C'],
    extensions: ['.c', '.h'],
    supportLevel: 'lsp',
    family: 'clang',
    serverLabel: 'clangd',
    serverCommands: ['clangd'],
    serverArgs: ['--background-index'],
    rootPatterns: ['compile_commands.json', 'compile_flags.txt', '.clangd', '.git'],
  },
  {
    id: 'cpp',
    aliases: ['C++', 'CPP', 'CXX'],
    extensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx'],
    supportLevel: 'lsp',
    family: 'clang',
    serverLabel: 'clangd',
    serverCommands: ['clangd'],
    serverArgs: ['--background-index'],
    rootPatterns: ['compile_commands.json', 'compile_flags.txt', '.clangd', '.git'],
  },
  {
    id: 'go',
    aliases: ['Go', 'Golang'],
    extensions: ['.go'],
    supportLevel: 'lsp',
    family: 'go',
    serverLabel: 'gopls',
    serverCommands: ['gopls'],
    serverArgs: [],
    rootPatterns: ['go.work', 'go.mod', '.git'],
  },
  {
    id: 'rust',
    aliases: ['Rust'],
    extensions: ['.rs'],
    supportLevel: 'lsp',
    family: 'rust',
    serverLabel: 'rust-analyzer',
    serverCommands: ['rust-analyzer'],
    serverArgs: [],
    rootPatterns: ['Cargo.toml', 'rust-project.json', '.git'],
  },
  {
    id: 'java',
    aliases: ['Java'],
    extensions: ['.java'],
    supportLevel: 'lsp',
    family: 'java',
    serverLabel: 'jdtls',
    serverCommands: ['jdtls'],
    serverArgs: [],
    rootPatterns: ['pom.xml', 'build.gradle', 'settings.gradle', '.git'],
  },
  {
    id: 'csharp',
    aliases: ['C#', 'CSharp', 'CS'],
    extensions: ['.cs', '.csx'],
    supportLevel: 'lsp',
    family: 'dotnet',
    serverLabel: 'OmniSharp',
    serverCommands: ['OmniSharp', 'omnisharp'],
    serverArgs: ['-lsp'],
    rootPatterns: ['*.sln', '*.csproj', '.git'],
  },
  {
    id: 'php',
    aliases: ['PHP'],
    extensions: ['.php', '.phtml'],
    supportLevel: 'lsp',
    family: 'php',
    serverLabel: 'phpactor',
    serverCommands: ['phpactor'],
    serverArgs: ['language-server'],
    rootPatterns: ['composer.json', '.git'],
  },
  {
    id: 'ruby',
    aliases: ['Ruby', 'RB'],
    extensions: ['.rb', '.erb', '.rake'],
    supportLevel: 'basic',
    family: 'ruby',
  },
  {
    id: 'kotlin',
    aliases: ['Kotlin', 'KT'],
    extensions: ['.kt', '.kts'],
    supportLevel: 'basic',
    family: 'jvm',
  },
  {
    id: 'swift',
    aliases: ['Swift'],
    extensions: ['.swift'],
    supportLevel: 'basic',
    family: 'swift',
  },
  {
    id: 'dart',
    aliases: ['Dart'],
    extensions: ['.dart'],
    supportLevel: 'basic',
    family: 'dart',
  },
  {
    id: 'scala',
    aliases: ['Scala'],
    extensions: ['.scala', '.sc'],
    supportLevel: 'basic',
    family: 'jvm',
  },
  {
    id: 'r',
    aliases: ['R'],
    extensions: ['.r', '.R'],
    supportLevel: 'basic',
    family: 'statistics',
  },
  {
    id: 'fortran',
    aliases: ['Fortran', 'F90'],
    extensions: ['.f', '.f90', '.f95', '.f03', '.f08'],
    supportLevel: 'basic',
    family: 'scientific',
  },
  {
    id: 'lua',
    aliases: ['Lua'],
    extensions: ['.lua'],
    supportLevel: 'basic',
    family: 'lua',
  },
  {
    id: 'perl',
    aliases: ['Perl'],
    extensions: ['.pl', '.pm'],
    supportLevel: 'basic',
    family: 'perl',
  },
  {
    id: 'shell',
    aliases: ['Shell', 'Bash', 'sh'],
    extensions: ['.sh', '.bash', '.zsh'],
    supportLevel: 'basic',
    family: 'shell',
  },
  {
    id: 'powershell',
    aliases: ['PowerShell', 'PS1'],
    extensions: ['.ps1', '.psm1'],
    supportLevel: 'basic',
    family: 'shell',
  },
  {
    id: 'sql',
    aliases: ['SQL'],
    extensions: ['.sql'],
    supportLevel: 'basic',
    family: 'database',
  },
  {
    id: 'xml',
    aliases: ['XML', 'XAML', 'SVG'],
    extensions: ['.xml', '.xaml', '.svg'],
    supportLevel: 'basic',
    family: 'markup',
  },
  {
    id: 'yaml',
    aliases: ['YAML', 'YML'],
    extensions: ['.yaml', '.yml'],
    supportLevel: 'basic',
    family: 'data',
  },
  {
    id: 'toml',
    aliases: ['TOML'],
    extensions: ['.toml'],
    supportLevel: 'basic',
    family: 'data',
  },
  {
    id: 'ini',
    aliases: ['INI', 'Config'],
    extensions: ['.ini', '.conf', '.properties'],
    supportLevel: 'basic',
    family: 'config',
  },
  {
    id: 'dockerfile',
    aliases: ['Dockerfile'],
    extensions: ['Dockerfile', '.dockerfile'],
    supportLevel: 'basic',
    family: 'infra',
  },
  {
    id: 'makefile',
    aliases: ['Makefile'],
    extensions: ['Makefile', '.mk'],
    supportLevel: 'basic',
    family: 'build',
  },
  {
    id: 'cmake',
    aliases: ['CMake'],
    extensions: ['.cmake', 'CMakeLists.txt'],
    supportLevel: 'basic',
    family: 'build',
  },
  {
    id: 'gradle',
    aliases: ['Gradle'],
    extensions: ['.gradle'],
    supportLevel: 'basic',
    family: 'build',
  },
  {
    id: 'groovy',
    aliases: ['Groovy'],
    extensions: ['.groovy', '.gvy'],
    supportLevel: 'basic',
    family: 'jvm',
  },
  {
    id: 'objective-c',
    aliases: ['Objective-C'],
    extensions: ['.m', '.mm'],
    supportLevel: 'basic',
    family: 'clang',
  },
  {
    id: 'haskell',
    aliases: ['Haskell'],
    extensions: ['.hs'],
    supportLevel: 'basic',
    family: 'functional',
  },
  {
    id: 'elixir',
    aliases: ['Elixir'],
    extensions: ['.ex', '.exs'],
    supportLevel: 'basic',
    family: 'beam',
  },
  {
    id: 'erlang',
    aliases: ['Erlang'],
    extensions: ['.erl', '.hrl'],
    supportLevel: 'basic',
    family: 'beam',
  },
  {
    id: 'clojure',
    aliases: ['Clojure'],
    extensions: ['.clj', '.cljs', '.cljc'],
    supportLevel: 'basic',
    family: 'lisp',
  },
  {
    id: 'fsharp',
    aliases: ['F#', 'FSharp'],
    extensions: ['.fs', '.fsi', '.fsx'],
    supportLevel: 'basic',
    family: 'dotnet',
  },
  {
    id: 'nim',
    aliases: ['Nim'],
    extensions: ['.nim'],
    supportLevel: 'basic',
    family: 'nim',
  },
  {
    id: 'zig',
    aliases: ['Zig'],
    extensions: ['.zig'],
    supportLevel: 'basic',
    family: 'systems',
  },
  {
    id: 'ocaml',
    aliases: ['OCaml'],
    extensions: ['.ml', '.mli'],
    supportLevel: 'basic',
    family: 'functional',
  },
  {
    id: 'julia',
    aliases: ['Julia'],
    extensions: ['.jl'],
    supportLevel: 'basic',
    family: 'scientific',
  },
  {
    id: 'matlab',
    aliases: ['MATLAB'],
    extensions: ['.m'],
    supportLevel: 'basic',
    family: 'scientific',
  },
  {
    id: 'solidity',
    aliases: ['Solidity'],
    extensions: ['.sol'],
    supportLevel: 'basic',
    family: 'blockchain',
  },
  {
    id: 'verilog',
    aliases: ['Verilog'],
    extensions: ['.v', '.vh'],
    supportLevel: 'basic',
    family: 'hardware',
  },
  {
    id: 'systemverilog',
    aliases: ['SystemVerilog'],
    extensions: ['.sv', '.svh'],
    supportLevel: 'basic',
    family: 'hardware',
  },
  {
    id: 'vhdl',
    aliases: ['VHDL'],
    extensions: ['.vhd', '.vhdl'],
    supportLevel: 'basic',
    family: 'hardware',
  },
  {
    id: 'assembly',
    aliases: ['Assembly', 'ASM'],
    extensions: ['.asm', '.s', '.S'],
    supportLevel: 'basic',
    family: 'systems',
  },
  {
    id: 'mips',
    aliases: ['MIPS'],
    extensions: ['.mips'],
    supportLevel: 'basic',
    family: 'systems',
  },
  {
    id: 'protobuf',
    aliases: ['Protocol Buffers', 'Proto'],
    extensions: ['.proto'],
    supportLevel: 'basic',
    family: 'data',
  },
  {
    id: 'graphql',
    aliases: ['GraphQL'],
    extensions: ['.graphql', '.gql'],
    supportLevel: 'basic',
    family: 'api',
  },
  {
    id: 'terraform',
    aliases: ['Terraform', 'HCL'],
    extensions: ['.tf', '.tfvars'],
    supportLevel: 'basic',
    family: 'infra',
  },
  {
    id: 'nginx',
    aliases: ['Nginx'],
    extensions: ['nginx.conf'],
    supportLevel: 'basic',
    family: 'infra',
  },
  {
    id: 'apache',
    aliases: ['Apache'],
    extensions: ['.htaccess'],
    supportLevel: 'basic',
    family: 'infra',
  },
  {
    id: 'latex',
    aliases: ['LaTeX', 'TeX'],
    extensions: ['.tex'],
    supportLevel: 'basic',
    family: 'document',
  },
  {
    id: 'plaintext',
    aliases: ['Plain Text'],
    extensions: ['.txt'],
    supportLevel: 'basic',
    family: 'text',
  },
];

export const EDITOR_LANGUAGE_BY_ID = Object.fromEntries(
  EDITOR_LANGUAGE_REGISTRY.map((entry) => [entry.id, entry])
);

export function getEditorLanguage(languageId) {
  return EDITOR_LANGUAGE_BY_ID[languageId] || null;
}

export function getEditorLanguagesBySupportLevel(supportLevel) {
  return EDITOR_LANGUAGE_REGISTRY.filter((entry) => entry.supportLevel === supportLevel);
}
