export const KEYBINDING_COMMANDS = [
  {
    id: 'workbench.action.showCommands',
    label: 'View: Show Command Palette',
    category: 'View',
    defaultBinding: 'ctrl+shift+p',
    keywords: ['command palette commands'],
  },
  {
    id: 'workbench.action.openSettings',
    label: 'Preferences: Open Settings',
    category: 'Preferences',
    defaultBinding: 'ctrl+,',
    keywords: ['settings preferences config'],
  },
  {
    id: 'workbench.action.openKeyboardShortcuts',
    label: 'Preferences: Open Keyboard Shortcuts',
    category: 'Preferences',
    defaultBinding: 'ctrl+k ctrl+s',
    keywords: ['keyboard shortcuts keybindings'],
  },
  {
    id: 'workbench.action.toggleKeyboardShortcuts',
    label: 'Preferences: Toggle Keyboard Shortcuts',
    category: 'Preferences',
    defaultBinding: 'ctrl+alt+k',
    keywords: ['keyboard shortcuts keybindings toggle'],
  },
  {
    id: 'workbench.action.showExtensions',
    label: 'View: Show Extensions',
    category: 'View',
    defaultBinding: 'ctrl+shift+x',
    keywords: ['extensions marketplace'],
  },
  {
    id: 'workbench.action.openAccount',
    label: 'Accounts: Open Account Center',
    category: 'Accounts',
    defaultBinding: 'ctrl+shift+a',
    keywords: ['account profile sync'],
  },
  {
    id: 'workbench.action.toggleSidebarVisibility',
    label: 'View: Toggle Primary Side Bar',
    category: 'View',
    defaultBinding: 'ctrl+b',
    keywords: ['sidebar explorer panel'],
  },
  {
    id: 'workbench.view.explorer',
    label: 'View: Show Explorer',
    category: 'View',
    defaultBinding: 'ctrl+shift+e',
    keywords: ['explorer files tree'],
  },
  {
    id: 'workbench.view.search',
    label: 'View: Show Search',
    category: 'View',
    defaultBinding: 'ctrl+shift+f',
    keywords: ['search find in files'],
  },
  {
    id: 'workbench.view.scm',
    label: 'View: Show Source Control',
    category: 'View',
    defaultBinding: 'ctrl+shift+g',
    keywords: ['git source control scm'],
  },
  {
    id: 'workbench.view.debug',
    label: 'View: Show Run and Debug',
    category: 'View',
    defaultBinding: 'ctrl+shift+d',
    keywords: ['debug run'],
  },
  {
    id: 'workbench.action.togglePanel',
    label: 'View: Toggle Bottom Panel',
    category: 'View',
    defaultBinding: 'ctrl+j',
    keywords: ['panel terminal bottom'],
  },
  {
    id: 'workbench.action.terminal.toggleTerminal',
    label: 'Terminal: Toggle Terminal',
    category: 'Terminal',
    defaultBinding: 'ctrl+`',
    keywords: ['terminal shell panel'],
  },
  {
    id: 'codeRunner.runFile',
    label: 'Code Runner: Run Current File',
    category: 'Code Runner',
    defaultBinding: 'ctrl+alt+n',
    keywords: ['run file code runner execute'],
  },
  {
    id: 'workbench.action.debug.start',
    label: 'Run and Debug: Start Debugging',
    category: 'Run & Debug',
    defaultBinding: 'f5',
    keywords: ['debug start'],
  },
  {
    id: 'workbench.action.debug.runWithoutDebugging',
    label: 'Run and Debug: Run Without Debugging',
    category: 'Run & Debug',
    defaultBinding: 'ctrl+f5',
    keywords: ['run without debugging'],
  },
  {
    id: 'workbench.action.debug.stop',
    label: 'Run and Debug: Stop Debugging',
    category: 'Run & Debug',
    defaultBinding: 'shift+f5',
    keywords: ['debug stop'],
  },
  {
    id: 'workbench.action.debug.restart',
    label: 'Run and Debug: Restart Debugging',
    category: 'Run & Debug',
    defaultBinding: 'ctrl+shift+f5',
    keywords: ['debug restart'],
  },
  {
    id: 'workbench.action.files.newUntitledFile',
    label: 'File: New Untitled File',
    category: 'File',
    defaultBinding: 'ctrl+n',
    keywords: ['new file untitled'],
  },
  {
    id: 'workbench.action.files.newFolder',
    label: 'File: New Folder',
    category: 'File',
    defaultBinding: 'ctrl+shift+n',
    keywords: ['new folder'],
  },
  {
    id: 'workbench.action.files.openFile',
    label: 'File: Open File',
    category: 'File',
    defaultBinding: 'ctrl+o',
    keywords: ['open file'],
  },
  {
    id: 'workbench.action.files.openFolder',
    label: 'File: Open Folder',
    category: 'File',
    defaultBinding: 'ctrl+k ctrl+o',
    keywords: ['open folder workspace'],
  },
  {
    id: 'workbench.action.quickOpen',
    label: 'Go: Quick Open',
    category: 'Go',
    defaultBinding: 'ctrl+p',
    keywords: ['quick open go to file'],
  },
  {
    id: 'workbench.action.gotoFile',
    label: 'Go: Go to File',
    category: 'Go',
    defaultBinding: 'ctrl+p',
    keywords: ['go file quick open'],
  },
  {
    id: 'workbench.action.gotoLine',
    label: 'Go: Go to Line',
    category: 'Go',
    defaultBinding: 'ctrl+g',
    keywords: ['go line'],
  },
  {
    id: 'workbench.action.splitEditorRight',
    label: 'View: Split Editor Right',
    category: 'View',
    defaultBinding: 'ctrl+\\',
    keywords: ['split editor right group'],
  },
  {
    id: 'workbench.action.splitEditorDown',
    label: 'View: Split Editor Down',
    category: 'View',
    defaultBinding: 'ctrl+k ctrl+\\',
    keywords: ['split editor down group'],
  },
  {
    id: 'workbench.action.gotoSymbolWorkspace',
    label: 'Go: Go to Symbol in Workspace',
    category: 'Go',
    defaultBinding: 'ctrl+t',
    keywords: ['workspace symbols'],
  },
  {
    id: 'workbench.action.gotoSymbolEditor',
    label: 'Go: Go to Symbol in Editor',
    category: 'Go',
    defaultBinding: 'ctrl+shift+o',
    keywords: ['editor symbols outline'],
  },
  {
    id: 'editor.action.revealDefinition',
    label: 'Go: Go to Definition',
    category: 'Go',
    defaultBinding: 'f12',
    keywords: ['definition'],
  },
  {
    id: 'editor.action.goToReferences',
    label: 'Go: Go to References',
    category: 'Go',
    defaultBinding: 'shift+f12',
    keywords: ['references'],
  },
  {
    id: 'workbench.action.files.save',
    label: 'File: Save',
    category: 'File',
    defaultBinding: 'ctrl+s',
    keywords: ['save file'],
  },
  {
    id: 'workbench.action.files.saveAs',
    label: 'File: Save As',
    category: 'File',
    defaultBinding: 'ctrl+shift+s',
    keywords: ['save as'],
  },
  {
    id: 'workbench.action.files.saveWorkspaceAs',
    label: 'File: Save Workspace As',
    category: 'File',
    defaultBinding: 'ctrl+alt+s',
    keywords: ['save workspace'],
  },
  {
    id: 'workbench.action.closeActiveEditor',
    label: 'View: Close Active Editor',
    category: 'View',
    defaultBinding: 'ctrl+w',
    keywords: ['close tab editor'],
  },
  {
    id: 'workbench.action.closeOtherEditors',
    label: 'View: Close Other Editors',
    category: 'View',
    defaultBinding: 'ctrl+alt+w',
    keywords: ['close others tabs'],
  },
  {
    id: 'workbench.action.closeAllEditors',
    label: 'View: Close All Editors',
    category: 'View',
    defaultBinding: 'ctrl+k ctrl+w',
    keywords: ['close all tabs'],
  },
  {
    id: 'workbench.action.focusNextGroup',
    label: 'View: Focus Next Editor Group',
    category: 'View',
    defaultBinding: 'ctrl+k ctrl+right',
    keywords: ['focus next group split editor'],
  },
  {
    id: 'workbench.action.focusPreviousGroup',
    label: 'View: Focus Previous Editor Group',
    category: 'View',
    defaultBinding: 'ctrl+k ctrl+left',
    keywords: ['focus previous group split editor'],
  },
  {
    id: 'workbench.action.closeActiveEditorGroup',
    label: 'View: Close Active Editor Group',
    category: 'View',
    defaultBinding: 'ctrl+k w',
    keywords: ['close editor group split'],
  },
  {
    id: 'workbench.action.moveEditorToNextGroup',
    label: 'View: Move Editor To Next Group',
    category: 'View',
    defaultBinding: 'ctrl+alt+right',
    keywords: ['move editor next group'],
  },
  {
    id: 'workbench.action.moveEditorToPreviousGroup',
    label: 'View: Move Editor To Previous Group',
    category: 'View',
    defaultBinding: 'ctrl+alt+left',
    keywords: ['move editor previous group'],
  },
  {
    id: 'workbench.action.reopenClosedEditor',
    label: 'View: Reopen Closed Editor',
    category: 'View',
    defaultBinding: 'ctrl+shift+t',
    keywords: ['reopen closed editor tab'],
  },
  {
    id: 'workbench.action.pinEditor',
    label: 'View: Pin Active Editor',
    category: 'View',
    defaultBinding: 'ctrl+k enter',
    keywords: ['pin editor tab'],
  },
  {
    id: 'explorer.rename',
    label: 'Explorer: Rename',
    category: 'Explorer',
    defaultBinding: 'f2',
    keywords: ['rename file folder'],
  },
  {
    id: 'edit.undo',
    label: 'Edit: Undo',
    category: 'Edit',
    defaultBinding: 'ctrl+z',
    keywords: ['undo'],
  },
  {
    id: 'edit.redo',
    label: 'Edit: Redo',
    category: 'Edit',
    defaultBinding: 'ctrl+y',
    keywords: ['redo'],
  },
  {
    id: 'edit.cut',
    label: 'Edit: Cut',
    category: 'Edit',
    defaultBinding: 'ctrl+x',
    keywords: ['cut'],
  },
  {
    id: 'edit.copy',
    label: 'Edit: Copy',
    category: 'Edit',
    defaultBinding: 'ctrl+c',
    keywords: ['copy'],
  },
  {
    id: 'edit.paste',
    label: 'Edit: Paste',
    category: 'Edit',
    defaultBinding: 'ctrl+v',
    keywords: ['paste'],
  },
  {
    id: 'edit.selectAll',
    label: 'Edit: Select All',
    category: 'Edit',
    defaultBinding: 'ctrl+a',
    keywords: ['select all'],
  },
  {
    id: 'edit.find',
    label: 'Edit: Find',
    category: 'Edit',
    defaultBinding: 'ctrl+f',
    keywords: ['find'],
  },
  {
    id: 'edit.replace',
    label: 'Edit: Replace',
    category: 'Edit',
    defaultBinding: 'ctrl+h',
    keywords: ['replace'],
  },
  {
    id: 'editor.action.formatDocument',
    label: 'Editor: Format Document',
    category: 'Editor',
    defaultBinding: 'shift+alt+f',
    keywords: ['format document'],
  },
  {
    id: 'editor.action.commentLine',
    label: 'Editor: Toggle Line Comment',
    category: 'Editor',
    defaultBinding: 'ctrl+/',
    keywords: ['comment toggle'],
  },
  {
    id: 'editor.action.toggleWordWrap',
    label: 'Editor: Toggle Word Wrap',
    category: 'Editor',
    defaultBinding: 'alt+z',
    keywords: ['word wrap'],
  },
];

export function getEffectiveBinding(command, customBindings) {
  if (Object.prototype.hasOwnProperty.call(customBindings, command.id)) {
    return customBindings[command.id];
  }

  return command.defaultBinding || '';
}
